version: '3.8'

services:
  postgres_db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    container_name: weather
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3472
      POSTGRES_DB: budgetbuddy_db
    ports:
      - 8080:80